language: dart
dart:
  - "2.0.0"
  - "2.1.0-dev.5.0"
os: 
  - linux
  - osx
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cloc ; fi
after_success:
  - echo "Build"
  - dart --snapshot=taurux.snapshot ./src/taurux.dart || exit 1
  - echo "Execution"
  - dart ./taurux.snapshot -h || exit 1
  - dart ./taurux.snapshot $EXAMPLE_LINK || exit 1
  - dart ./taurux.snapshot $EXAMPLE_LINK --target /tmp || exit 1
  - dart ./taurux.snapshot $EXAMPLE_LINK --target /tmp --name foo --cbr 128 || exit 1
  - du -h $EXAMPLE_FILE || exit 1
  - du -h /tmp/$EXAMPLE_FILE || exit 1
  - du -h /tmp/foo.mp3 || exit 1
  - echo "Cleanup"
  - rm $EXAMPLE_FILE || exit 1
  - rm /tmp/$EXAMPLE_FILE || exit 1
  - rm /tmp/foo.mp3 || exit 1
  - echo "Finished"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cloc ./src ; fi
script:
  - echo $?