language: dart
dart:
  - "2.0.0"
os: 
  - linux
  - osx
after_success:
  - echo "After Success"
  - dart --snapshot=taurus.snapshot ./src/taurus.dart
  - dart ./taurus.snapshot -h
  - echo "Finished"
