language: dart
dart:
  - "2.0.0"
os: 
  - linux
  - osx
after_success:
  - echo "After Success"
  - dart --snapshot=taurux.snapshot ./src/taurux.dart || exit 1
  - dart ./taurux.snapshot -h || exit 1
  - echo "Finished"
