language: dart
dart:
  - "2.0.0"
os: 
  - linux
  - osx
after_success:
  - echo "After Success"
  - dart ./taurus.dart -h
  - dart https://www.redbullradio.com/shows/main-stage/episodes/efdemin-live-at-nachtdigital-2011--3 -D --target /tmp
  - rm /tmp/efdemin-live-at-nachtdigital-2011--3.mp3
  - echo "Finished"
