language: dart
dart:
  - dev
  - stable
dart_task:
  - test: ./test/* --reporter expanded
    xvfb: false
  - dart_codecov_generator
os:
  - linux
  - osx
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cloc ; fi
after_success:
  - echo "Build"
  - dart --snapshot=taurux.snapshot ./src/taurux.dart || exit 1
  - echo "Execution"
  - dart ./taurux.snapshot -h || exit 1
  - if [[ "$USE_TAURUX" == "true" ]]; then ./scripts/use_taurux.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cloc ./src ./test ; fi
