language: dart
dart:
  - "2.0.0"
  - "2.1.0-dev.5.0"
  - dev
  - stable
dart_task:
  - test: ./test/*
    xvfb: false
os:
  - linux
  - osx
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cloc ; fi
after_success:
  - echo "Build"
  - dart --snapshot=taurux.snapshot ./src/taurux.dart || exit 1
  - echo "Execution"
  - dart ./taurux.snapshot -h || exit 1
  - if [[ "$USE_TAURUX" == "true" ]]; then ./scripts/use_taurux.sh ; fi
  - if [[ "$TEST_TAURUX" == "true" ]]; then ./scripts/start_tests.sh || exit 1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cloc ./src ./test ; fi
