language: dart
dart:
  - "1.9.0"
  - "2.0.0"
os: 
  - linux
  - osx
notifications:
  email:
    on_success: always 
    on_failure: always
after_success:
  - echo "After Success"
  - dart --snapshot=taurus.snapshot ./taurus.dart || exit 1
  - dart ./taurus.snapshot -h || exit 1
  - echo "Finished"
