name: taurux
description: A PoC for the Taurux App
homepage: https://github.com/0xflotus/taurux
version: 0.1.0
author: 0xflotus

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: any
  html: any
  args: any
  test: any
  coverage: "^0.7.0"
  dart_codecov_generator: "^0.4.0"

publish_to: none
