name: taurux
description: A PoC for the Taurux App
homepage: https://github.com/0xflotus/taurux
version: 0.1.0
author: 0xflotus

environment:
  sdk: '>=2.0.1 <3.0.0'

dependencies:
  http: any
  html: any
  args: any
  test: any

publish_to: none
