version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installation
          command: pub get
      - run:
          name: Test
          command: pub run test test/* --reporter expanded
